package net.runelite.client.owo;

public enum LogicType {
    NO_OP, GEMSTONE_CRAB, WOODCUTTING, SLAYER, AGILITY_COURSE,
    SMELT_GOLD_BRACELET, SMELT_STEEL_BAR, SMELT_MITHRIL_BAR,
    ALCHER, WINE_BUYER, ARDY_KNIGHTS, SHILO_SMELTER, CHINS,
    LEAGUE_ALDARIN_GEM
}
